## STATIC CONFIGURATION
global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO
accessLog: {}

api:
  insecure: true
  dashboard: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: /config
    watch: true

certificatesResolvers:
  myresolver:
    acme:
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      email: email@gmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
